cc_library(
    name = "arrays_and_stringslib",
    srcs = ["num_matching_subsequence.cc",
    "lc1004_max_consecutive_ones_iii.cc"],
    hdrs = ["mystrings.h"],
    visibility = ["//visibility:public"],
)
