load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "graph_shortestpath_tests",
    srcs = ["graph_shortestpath_tests.cc"],
    deps = [
        "//src/search:searchlib",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "tree_tests",
    srcs = ["tree_tests.cc"],
    deps = [
        "//src:treelib",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "twosum_tests",
    srcs = ["twosum_tests.cc"],
    deps = [
        "//src:twosum",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "weirdalgo_tests",
    srcs = ["weirdalgo_tests.cc"],
    deps = [
        "//src:weirdalgo",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "missingnum_tests",
    srcs = ["missingnum_tests.cc"],
    deps = [
        "//src:missingnum",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "introductory_cses_tests",
    srcs = ["introductory_cses_tests.cc"],
    deps = [
        "//src:introductoryproblems_cses",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "arr_and_strtests",
    srcs = ["arr_and_strtests.cc"],
    deps = [
        "//src/arrays_and_strings:arrays_and_stringslib",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "hashtests",
    srcs = ["hashtests.cc"],
    deps = [
        "//src/hashing:hashinglib",
        "@com_google_googletest//:gtest_main",
    ],
)
cc_test(
    name = "bit_twiddling_tests",
    srcs = ["bit_twiddling_tests.cc"],
    deps = [
        "//src/bit_twiddling:bit_twiddling_lib",
        "@com_google_googletest//:gtest_main",
    ],
)