load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "graph_shortestpath_tests",
    srcs = ["graph_shortestpath_tests.cc"],
    deps = [
        "//src/search:searchlib",
        "@com_google_googletest//:gtest_main",
    ],
)