cc_test(
    name = "comparchfuncmodel_tests",
    srcs = ["comparchfuncmodel_tests.cc"],
    deps = [
        "//src/comparchfuncmodel:comparchfuncmodel_lib",
        "@com_google_googletest//:gtest_main",
    ],
)