cc_test(
    name = "recursion_reverselinkedlist_tests",
    srcs = ["recursion_reverselinkedlist_tests.cc"],
    deps = [
        "//src:recursion_lib",
        "@com_google_googletest//:gtest_main",
    ],
)