cc_library(
    name = "hashinglib",
    srcs = ["findWinners.cc",
    "maximumSum.cc",
    "canConstruct.cc",
    "isPathCrossing.cc",
    "findLucky.cc",
    "frequencySort.cc",
    "lc930_binary_subarrays_with_sum.cc",
    "lc1695_maximum_erasure_value.cc",
    "lc567_permutation_in_string.cc"],
    hdrs = ["myhash.h"],
    visibility = ["//visibility:public"],
)
