load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "treelib",
    srcs = ["tree.cc"],
    hdrs = ["tree.h"],
    visibility = ["//visibility:public"],
)


cc_library(
    name = "twosum",
    srcs = ["twosum.h"],
    visibility = ["//visibility:public"],
)